### PR TITLE
making a shell of a README

### PR DESCRIPTION
**Pull request by nh13**

### CODE REVIEW

**Comment by tfenne** [comment]
How does this relate to the larger documentation project?  Is the idea to edit this here then copy it to the doc repo?

**Comment by nh13** [comment]
I figure we need something now, and the other documentation project can continue forward.

**Comment by nh13** [comment]
We should have a link to the `Linker` task (when ready) in the section " List of features" in the sub-section "Mechanisms for passing state".  See https://github.com/fulcrumgenomics/dagr/pull/97

**Comment by nh13** [comment]
for the example Pipeline, do we want to include the imports?

**Comment by nh13** [comment]
@tfenne just a few more questions, and I'd lock to block on the `Linker` PR.

**Comment by tfenne** [comment]
@nh13 I don't think we should include the imports etc. for the example pipeline - I think that's just boilerplate that will make it look more intimidating.  If you want we could provide a link into the actual file in the repo also?

**Comment by nh13** [comment]
@tfenne all set, rebase and merge.

**Comment by tfenne** [comment]
How did this become mine to rebase and merge?  This is your PR :stuck_out_tongue:

**Pull request merged**
